on:
    push:
        branches:
            - main



jobs:
    build:
        runs-on: ubuntu-latest


        steps:
            - uses : actions/checkout@v3

            - name : "LoginToDockerHub"
              run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}

            - name : "build myimage"
              run: docker build -t ${{ secrets.DOCKER_USERNAME }}/dockerproject .


            - name : "push to dockerhub"
              run: docker push ${{ secrets.DOCKER_USERNAME }}/dockerproject